# Generated by Django 5.2.14 on 2026-05-28 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag_type', models.CharField(choices=[('outcome', 'Outcome'), ('organisation', 'Organisation')], max_length=20)),
                ('colour', models.CharField(default='#6366f1', help_text='Hex colour, e.g. #6366f1', max_length=7)),
            ],
            options={
                'ordering': ['tag_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('activity', 'Activity'), ('milestone', 'Milestone'), ('metric', 'Metric')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5)),
                ('prd_link', models.URLField(blank=True)),
                ('backlog_link', models.URLField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('linked_activities', models.ManyToManyField(blank=True, limit_choices_to={'item_type': 'activity'}, related_name='linked_milestones_metrics', to='roadmap.item')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='roadmap.roadmap')),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='roadmap.tag')),
            ],
            options={
                'ordering': ['start_date', 'title'],
            },
        ),
    ]
