# Generated by Django 5.2.14 on 2026-05-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='organisation',
            field=models.CharField(blank=True, help_text='The organisation this roadmap belongs to', max_length=200),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='roadmaps', to='roadmap.tag'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
