# Generated by Django 5.2.14 on 2026-05-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_roadmap_mission_roadmap_organisation_roadmap_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('outcome', 'Defra Outcome'), ('gov_objective', 'Gov Objective'), ('organisation', 'Organisation')], max_length=20),
        ),
    ]
