# Generated by Django 5.2.14 on 2026-05-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_tag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('outcome', 'Defra Outcome'), ('gov_objective', 'Gov Objective'), ('organisation', 'Team')], max_length=20),
        ),
    ]
