# Generated by Django 5.2.14 on 2026-06-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_alter_tag_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('outcome', 'Defra Outcome'), ('gov_objective', 'Gov Objective'), ('organisation', 'Team'), ('workstream', 'Workstream')], max_length=20),
        ),
    ]
