# Generated by Django 5.2.14 on 2026-06-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0007_alter_tag_tag_type'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE roadmap_tag SET colour = '#595959' WHERE colour IS NOT NULL;",
            reverse_sql="UPDATE roadmap_tag SET colour = '#6366f1' WHERE colour = '#595959';",
        ),
    ]
