# Generated by Django 5.2.14 on 2026-06-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0011_remove_roadmap_organisation_tag_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(default='#595959', help_text='Hex colour, e.g. #595959', max_length=7),
        ),
    ]
