# Generated by Django 5.2.14 on 2026-06-21 20:55

import roadmap.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0013_backfill_roadmap_tag_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(default=roadmap.models.random_tag_colour, help_text='Hex colour, e.g. #1d70b8', max_length=7),
        ),
    ]
