# Generated by Django 5.2.14 on 2026-07-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0015_backfill_tag_colours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='link',
            field=models.URLField(blank=True, help_text='Optional third-party link with more information'),
        ),
    ]
