# Generated by Django 5.2.14 on 2026-07-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0016_tag_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Manual swim-lane order (lower = higher up)'),
        ),
    ]
