# Generated by Django 5.2.14 on 2026-08-03 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0017_tag_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Manual swim-lane order on roadmaps (lower = higher up)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='roadmap',
            name='sync_okrs',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, help_text='e.g. %, £, users', max_length=20)),
                ('start_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('direction', models.CharField(choices=[('increase', 'Increase (higher is better)'), ('decrease', 'Decrease (lower is better)')], default='increase', max_length=10)),
                ('status', models.CharField(choices=[('on_track', 'On track'), ('at_risk', 'At risk'), ('off_track', 'Off track'), ('achieved', 'Achieved')], default='on_track', max_length=12)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='roadmap.objective')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='roadmap.objective'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='applied_roadmaps', to='roadmap.objective'),
        ),
        migrations.CreateModel(
            name='ObjectiveSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('group', 'Organisation'), ('team', 'Team')], default='group', max_length=10)),
                ('name', models.CharField(help_text='e.g. "FY26 Q1"', max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('period', models.CharField(blank=True, choices=[('quarterly', 'Quarterly'), ('annual', 'Annual')], help_text='quarterly / annual when created from a preset; blank for a custom date range.', max_length=10, null=True)),
                ('archived', models.BooleanField(default=False, help_text='Hidden from active lists; kept for reference.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_sets', to='roadmap.organisation')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='objective',
            name='objective_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='roadmap.objectiveset'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='objective_sets',
            field=models.ManyToManyField(blank=True, related_name='roadmaps', to='roadmap.objectiveset'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Manual ordering (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='roadmap.organisation')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='objectiveset',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objective_sets', to='roadmap.team'),
        ),
        migrations.AddField(
            model_name='objective',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='roadmap.team'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='owning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmaps', to='roadmap.team'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='unique_team_per_org'),
        ),
        migrations.AddConstraint(
            model_name='objectiveset',
            constraint=models.UniqueConstraint(fields=('organisation', 'scope', 'team', 'name'), name='unique_objective_set_scope_name'),
        ),
        migrations.AddConstraint(
            model_name='objectiveset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'group'), ('team__isnull', True)), models.Q(('scope', 'team'), ('team__isnull', False)), _connector='OR'), name='objective_set_scope_team_consistency'),
        ),
    ]
