# Generated by Django 5.2.14 on 2026-07-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0017_tag_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('activity', 'Activity'), ('milestone', 'Milestone'), ('metric', 'Key Result')], max_length=20),
        ),
    ]
