# Generated by Django 5.2.14 on 2026-08-03 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0018_okr_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad_tags', to='roadmap.team'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='roadmap',
            field=models.ForeignKey(blank=True, help_text='Set for roadmap-scoped tags (squads, objectives); null for central tags.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_tags', to='roadmap.roadmap'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('outcome', 'Defra Outcome'), ('gov_objective', 'Gov Objective'), ('objective', 'Objective'), ('organisation', 'Squad'), ('category', 'Item Category')], max_length=20),
        ),
    ]
