# Generated by Django 5.2.14 on 2026-08-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0021_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='row',
            field=models.PositiveIntegerField(blank=True, help_text='Manual row in the track (0 = top). Blank = stack automatically.', null=True),
        ),
    ]
