# Generated by Django 5.2.14 on 2026-08-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0018_alter_item_item_type'),
        ('roadmap', '0022_item_row'),
    ]

    operations = [
    ]
