# Generated by Django 5.2.14 on 2026-08-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0023_merge_0018_alter_item_item_type_0022_item_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyresult',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='row',
            field=models.PositiveIntegerField(blank=True, help_text='Manual row in the key-results track (0 = top). Blank = auto-stack.', null=True),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
