# Generated by Django 5.2.14 on 2026-08-10 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0024_keyresult_dates_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyresult',
            name='objective_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_results', to='roadmap.objectiveset'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='hidden_objectives',
            field=models.ManyToManyField(blank=True, related_name='hidden_on_roadmaps', to='roadmap.objective'),
        ),
    ]
