# Generated by Django 5.2.14 on 2026-10-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0027_item_key_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='archived',
            field=models.BooleanField(default=False, help_text='Hidden from the active roadmap list; kept for reference.'),
        ),
    ]
