# Generated by Django 5.2.14 on 2026-10-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0028_roadmap_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='member_objectives', to='roadmap.objectiveset'),
        ),
    ]
