# Generated by Django 5.2.14 on 2026-10-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0030_backfill_objective_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyresult',
            name='archived',
            field=models.BooleanField(default=False, help_text='Hidden from the roadmap timeline and active lists; kept for reference.'),
        ),
        migrations.AddField(
            model_name='objective',
            name='archived',
            field=models.BooleanField(default=False, help_text='Hidden from roadmap lanes and active lists; kept for reference.'),
        ),
    ]
